name: dbt test

on:
  push:         # run when you push to any branch
  pull_request: # run when PR is opened/updated
  workflow_dispatch: # allow manual run in GitHub

jobs:
  run-dbt-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dbt
        run: |
          pip install dbt-core dbt-postgres  # change adapter if needed (snowflake, bigquery, etc.)

      - name: Run dbt debug
        run: dbt debug

      - name: Run dbt test
        run: dbt test
