name: dbt test

on:
 # push:
 # pull_request:
  workflow_dispatch:

jobs:
  run-dbt-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dbt with Snowflake adapter
        run: |
          pip install dbt-core dbt-snowflake

      - name: Create profiles.yml
        run: |
          mkdir -p ~/.dbt
          cat > ~/.dbt/profiles.yml <<EOL
          newdw:
            target: dev
            outputs:
              dev:
                type: snowflake
                account: XCPCNDY-WG64940
                user: ANGELOALFONSO
                password: VnpZWXpwnvf2Z4K
                role: ACCOUNTADMIN
                warehouse: COMPUTE_WH
                database: MSITDBTSNOWGIT
                schema: DWPRACTICE
                threads: 1
          EOL

      - name: Run dbt debug
        run: dbt debug --profile newdw

      - name: Run dbt test
        run: dbt test --profile newdw
