name: dbt test

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  run-dbt-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dbt with Snowflake adapter
        run: |
          pip install dbt-core dbt-snowflake

      - name: Create profiles.yml
        run: |
          mkdir -p ~/.dbt
          cat > ~/.dbt/profiles.yml <<EOL
          newdw:
            target: dev
            outputs:
              dev:
                type: snowflake
                account: XCPCNDY-WG64940
                user: ANGELOALFONSO
                password: VnpZWXpwnvf2Z4K
                role: ACCOUNTADMIN
                warehouse: COMPUTE_WH
                database: MSITDBTSNOWGIT
                schema: DWPRACTICE
                threads: 1
          EOL

      - name: Run dbt debug
        run: dbt debug --profile newdw

      - name: Run dbt test
        run: dbt test --profile newdw

      # 👉 NEW STEP: Run your Python script to generate report
      - name: Generate Data Quality Report
        run: |
          pip install -r requirements.txt || true   # install any needed libs
          python scripts/dq_report.py

      # 👉 OPTIONAL: Deploy docs/ (report) to GitHub Pages
      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs
