name: Data Quality Report

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install Python dependencies
        run: |
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      # Install dbt
      - name: Install dbt
        run: |
          pip install dbt-core dbt-postgres   # or dbt-snowflake/dbt-bigquery depending on your adapter

      # Run dbt test to generate target/run_results.json
      - name: Run dbt tests
        run: |
          dbt deps        # if you use packages
          dbt seed --full-refresh || true   # optional if you have seeds
          dbt run || true                   # optional if you want full models
          dbt test                          # generates target/run_results.json

      # Now run your report script
      - name: Generate Data Quality Report
        run: |
          python scripts/dq_report.py

      # Deploy report to GitHub Pages
      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs
