name: Data Quality Report

on:
  workflow_dispatch:   # run manually from Actions tab
  # schedule:          # optional, uncomment to run automatically
  #   - cron: "0 0 * * *"  # every day at midnight UTC

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      # 3. Install dependencies (if you have requirements.txt)
      - name: Install dependencies
        run: |
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      # 4. Run your Python report script
      - name: Generate report
        run: |
          python scripts/dq_report.py

      # 5. Upload report to GitHub Pages
      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs   # will include dbt_data_quality_report.html

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
