version: 2

seeds:
  - name: AccountStatus
    description: "{{ doc('account_status') }}"
    columns:
      - name: StatusCode
        description: "Unique code identifying the account status."
        tests:
          - not_null
          - unique
      - name: Description
        description: "Text description of the account status."
      - name: CreatedDate
        description: "Original date of creation in source data."

  - name: Branch
    description: "{{ doc('branch') }}"
    columns:
      - name: BranchID
        description: "Unique identifier for the branch."
        tests:
          - not_null
          - unique
      - name: Description
        description: "Name or label of the branch."
      - name: Cluster
        description: "Operational or regional cluster the branch belongs to."
      - name: City
        description: "City where the branch is located."
      - name: Province
        description: "Province where the branch is located."
      - name: ZipCode
        description: "Postal code of the branch location."        


sources:
  - name: snow_source
    description: "Source tables from SNOW"
    database: MSITDBTSNOWGIT
    schema: public
    tables:
      - name: reservationhdr   # match lowercase
        description: "{{ doc('source_reservationhdr') }}"
        freshness:
          warn_after: {count: 1, period: day}
          error_after: {count: 2, period: day}
        loaded_at_field: reservationdate   # also lowercase column name

  - name: seeds
    database: MSITDBTSNOWGIT
    schema: SEEDS
    tables:
      - name: RESERVATIONHDRFORDEMO

        description: "{{ doc('source_reservationhdrfordemo') }}"

