version: 2

seeds:
  - name: AccountStatus
    description: "Reference data for account statuses, loaded from CSV."
    columns:
      - name: StatusCode
        description: "Unique code identifying the account status."
        tests:
          - not_null
          - unique
      - name: Description
        description: "Text description of the account status."
      - name: CreatedDate
        description: "Original date of creation in source data."
        
models:
  - name: stg_account_status
    description: "Staging model for account status reference data seeded from CSV."
    columns:
      - name: status_code
        description: "Unique code identifying the account status."
        tests:
          - not_null
          - unique

      - name: status_description
        description: "Text description of the account status."
        tests:
          - not_null

      - name: created_date
        description: "Date when the status was created in the system."

  - name: dim_account_status
    description: "Dimension table for account statuses"
    columns:
      - name: status_code
        description: "Status code as string"
        tests:
          - unique
          - not_null
      - name: status_description
        description: "Status description"
      - name: created_date
        description: "Date the status was created"

sources:
  - name: neon_source
    description: "Source tables from Neon Postgres"
    database: source
    schema: public
    tables:
      - name: reservationhdr   # match lowercase
        description: "Reservation header table"
        freshness:
          warn_after: {count: 1, period: day}
          error_after: {count: 2, period: day}
        loaded_at_field: reservationdate   # also lowercase column name
