version: 2

seeds:
  - name: AccountStatus
    description: "Reference data for account statuses, loaded from CSV."
    columns:
      - name: StatusCode
        description: "Unique code identifying the account status."
        tests:
          - not_null
          - unique
      - name: Description
        description: "Text description of the account status."
      - name: CreatedDate
        description: "Original date of creation in source data."
        
models:
  - name: stg_account_status
    description: "Staging model for account status reference data seeded from CSV."
    columns:
      - name: status_code
        description: "Unique code identifying the account status."
        tests:
          - not_null
          - unique

      - name: status_description
        description: "Text description of the account status."
        tests:
          - not_null

      - name: created_date
        description: "Date when the status was created in the system."
