version: 2

seeds:
  - name: AccountStatus
    description: "{{ doc('account_status') }}"
    columns:
      - name: StatusCode
        description: "Unique code identifying the account status."
        tests:
          - not_null
          - unique
      - name: Description
        description: "Text description of the account status."
      - name: CreatedDate
        description: "Original date of creation in source data."

  - name: Branch
    description: "{{ doc('branch') }}"
    columns:
      - name: BranchID
        description: "Unique identifier for the branch."
        tests:
          - not_null
          - unique
      - name: Description
        description: "Name or label of the branch."
      - name: Cluster
        description: "Operational or regional cluster the branch belongs to."
      - name: City
        description: "City where the branch is located."
      - name: Province
        description: "Province where the branch is located."
      - name: ZipCode
        description: "Postal code of the branch location."
  
  - name: UnitType
    description: "{{ doc('dim_unittype') }}"
    columns:
      - name: UnitTypeCode
        description: "Unique identifier for the unit type."
        tests:
          - not_null
          - unique
      - name: Description
        description: "Business-friendly label of the unit type."
      - name: RecDate
        description: "Timestamp of the latest update to the unit type record."

  - name: UnitClass
    description: "{{ doc('unitclass') }}"
    columns:
      - name: UnitClassCode
        description: "Unique code identifying the unit class."
        tests:
          - not_null
          - unique
      - name: Description
        description: "Text description of the unit class."
      - name: RecDate
        description: "Original date of creation or update in source data."

  - name: FinancingType
    description: "{{ doc('financingtype') }}"
    columns:
      - name: FinTypeCode
        description: "Unique code identifying the financing type."
        tests:
          - not_null
          - unique
      - name: Description
        description: "Text description of the financing type."
      - name: RecDate
        description: "Date the financing type record was created."

  - name: SourceOfSale
    description: "{{ doc('source_of_sale') }}"
    columns:
      - name: sourcecode
        description: "Unique code identifying the source of sale."
        tests:
          - not_null
          - unique
      - name: description
        description: "Text description of the source of sale."
      - name: recdate
        description: "Original record date from the source system."

  - name: LotInventory
    description: "{{ doc('lotinventory') }}"
    columns:
      - name: unitcode
        description: "Unique code identifying the unit."
        tests:
          - not_null
          - unique
      - name: branchid
        description: "Identifier for the branch where the unit is located."
      - name: unittype
        description: "Type of the unit (e.g., Lawn Lot, Garden Niche)."
      - name: unitclass
        description: "Classification of the unit."
      - name: phase
        description: "Development phase of the unit."
      - name: section
        description: "Section within the development."
      - name: block
        description: "Block number or identifier."
      - name: lot
        description: "Lot number or identifier."
      - name: unitcost
        description: "Cost of the unit."
      - name: recuser
        description: "User who recorded the entry."
      - name: recdate
        description: "Date and time the record was created."



models:
  - name: stg_account_status
    description: "{{ doc('stg_account_status') }}"
    columns:
      - name: status_code
        description: "Unique code identifying the account status."
        tests:
          - not_null
          - unique

      - name: status_description
        description: "Text description of the account status."
        tests:
          - not_null

      - name: created_date
        description: "Date when the status was created in the system."
    
  - name: stg_branch
    description: "{{ doc('stg_branch') }}"
    columns:
      - name: branchid
        description: "Unique identifier for the branch."
        tests:
          - not_null
          - unique

      - name: description
        description: "Name or label of the branch."
        tests:
          - not_null

      - name: cluster
        description: "Operational or regional cluster the branch belongs to."
        tests:
         - not_null

      - name: city
        description: "City where the branch is located."
        tests:
          - not_null

      - name: province
        description: "Province where the branch is located."
        tests:
          - not_null

      - name: zipcode
        description: "Postal code of the branch location."
        tests:
          - not_null

  - name: stg_reservationhdr
    description: "{{ doc('stg_reservationhdr') }}"
    columns:
      - name: transaction_id
        description: "Primary key of the reservation"
        tests:
          - unique
          - not_null

      - name: branch_id
        description: "Branch identifier"

      - name: reservation_date
        description: "Date and time when the reservation was made"
        tests:
          - not_null

      - name: client_id
        description: "Foreign key to client"

      - name: status_code
        description: "Reservation status"

      - name: lot_price
        description: "Lot price before taxes/discounts"

      - name: tcp
        description: "Total contract price"

  - name: stg_unittype
    description: "{{ doc('stg_unittype') }}"
    columns:
      - name: unittypecode
        description: "Unique identifier for the unit type."
        tests:
          - not_null
          - unique

      - name: description
        description: "Business-friendly label of the unit type."
        tests:
          - not_null

      - name: recdate
        description: "Timestamp of the latest update to the unit type record."
        tests:
          - not_null

  - name: stg_unitclass
    description: "{{ doc('stg_unitclass') }}"
    columns:
      - name: unitclasscode
        description: "Unique code identifying the unit class."
        tests:
          - not_null
          - unique

      - name: description
        description: "Text description of the unit class."
        tests:
          - not_null

      - name: recdate
        description: "Date when the unit class was created or last updated."

  - name: stg_financingtype
    description: "{{ doc('stg_financingtype') }}"
    columns:
      - name: fintypecode
        description: "Unique identifier for the financing type."
        tests:
          - not_null
          - unique
      - name: description
        description: "Name or label of the financing type."
        tests:
          - not_null
      - name: recdate
        description: "Date the financing type was recorded."
        tests:
          - not_null

  - name: stg_source_of_sale
    description: "{{ doc('stg_source_of_sale') }}"
    columns:
      - name: sourcecode
        description: "Unique identifier for the source of sale."
        tests:
          - not_null
          - unique
      - name: description
        description: "Name or label of the source of sale."
        tests:
          - not_null
      - name: recdate
        description: "Timestamp when the source of sale was recorded."
        tests:
          - not_null

  - name: stg_lotinventory
    description: "{{ doc('stg_lotinventory') }}"
    columns:
      - name: unitcode
        description: "Unique identifier for the unit."
        tests:
          - not_null
          - unique
      - name: branchid
        description: "Branch ID associated with the unit."
        tests:
          - not_null
      - name: unittype
        description: "Type of unit."
        tests:
          - not_null
      - name: unitclass
        description: "Class of unit."
        tests:
          - not_null
      - name: phase
        description: "Phase of development."
        tests:
          - not_null
      - name: section
        description: "Section of the development."
        tests:
          - not_null
      - name: block
        description: "Block identifier."
        tests:
          - not_null
      - name: lot
        description: "Lot identifier."
        tests:
          - not_null
      - name: unitcost
        description: "Cost of the unit."
        tests:
          - not_null
      - name: recuser
        description: "User who recorded the unit."
        tests:
          - not_null
      - name: recdate
        description: "Timestamp of record creation."
        tests:
          - not_null


  - name: dim_account_status
    description: "{{ doc('dim_account_status') }}"
    columns:
      - name: status_code
        description: "Status code as string"
        tests:
          - unique
          - not_null
      - name: status_description
        description: "Status description"
      - name: created_date
        description: "Date the status was created"

  - name: fact_reservations
    description: "{{ doc('fact_reservations') }}"
    columns:
      - name: transaction_id
        description: "Unique identifier for each reservation transaction."
        tests:
          - unique
          - not_null

      - name: branch_id
        description: "Foreign key reference to branch dimension."
        tests:
          - not_null

      - name: client_id
        description: "Foreign key reference to client dimension."
        tests:
          - not_null

      - name: unit_code
        description: "Foreign key reference to unit dimension."
        tests:
          - not_null

      - name: status_code
        description: "Reservation status code."
        tests:
          - not_null

      - name: finance_type_code
        description: "Reservation finance type code."
        tests:
          - not_null

      - name: source_code
        description: "Reservation source code."
        tests:
          - not_null

      - name: lot_price
        description: "Base price of the lot."

      - name: vat
        description: "Value-added tax amount."

      - name: gross_lot_price
        description: "Gross price of the lot including VAT."

      - name: sales_disc
        description: "Sales discount applied to the reservation."

      - name: net_lot_price
        description: "Net lot price after discounts."

      - name: misc
        description: "Miscellaneous charges."

      - name: tcp
        description: "Total contract price."

      - name: reservation_date
        description: "Date the reservation was created."
        tests:
          - not_null

  - name: dim_branch
    description: "{{ doc('dim_branch') }}"
    columns:
    - name: branchid
      description: "Branch ID as integer"
      tests:
        - unique
        - not_null

    - name: description
      description: "Branch name or label"

    - name: cluster
      description: "Cluster grouping for the branch"

  - name: dim_unittype
    description: "{{ doc('dim_unittype') }}"
    columns:
      - name: unittypecode
        description: "Unit type code as string identifier"
        tests:
          - unique
          - not_null

      - name: description
        description: "Business-friendly label of the unit type"

      - name: recdate
        description: "Timestamp of the latest update to the unit type record"

  - name: dim_unitclass
    description: "{{ doc('dim_unitclass') }}"
    columns:
      - name: unitclasscode
        description: "Unit class code as string"
        tests:
          - unique
          - not_null
      - name: description
        description: "Unit class description"
      - name: recdate
        description: "Date the unit class was created or updated"

  - name: dim_financingtype
    description: "{{ doc('dim_financingtype') }}"
    columns:
      - name: fintypecode
        description: "Financing type code as string."
        tests:
          - not_null
          - unique
      - name: description
        description: "Financing type description."
      - name: recdate
        description: "Date the financing type was recorded."

  - name: dim_source_of_sale
    description: "{{ doc('dim_source_of_sale') }}"
    columns:
      - name: source_code
        description: "Source code as string."
        tests:
          - not_null
          - unique
      - name: source_description
        description: "Description of the source of sale."
      - name: record_date
        description: "Date the source of sale was recorded."

  - name: dim_lotinventory
    description: "{{ doc('dim_lotinventory') }}"
    columns:
      - name: unit_code
        description: "Unique code for the unit."
        tests:
          - not_null
          - unique
      - name: branch_id
        description: "Branch identifier."
      - name: unit_type
        description: "Type of the unit."
      - name: unit_class
        description: "Classification of the unit."
      - name: phase
        description: "Development phase."
      - name: section
        description: "Section within the development."
      - name: block
        description: "Block identifier."
      - name: lot
        description: "Lot identifier."
      - name: unit_cost
        description: "Cost of the unit."
      - name: recorded_by
        description: "User who recorded the unit."
      - name: record_date
        description: "Date the unit was recorded."




sources:
  - name: snow_source
    description: "Source tables from SNOW"
    database: MSITDBTSNOWGIT
    schema: public
    tables:
      - name: reservationhdr   # match lowercase
        description: "{{ doc('source_reservationhdr') }}"
        freshness:
          warn_after: {count: 1, period: day}
          error_after: {count: 2, period: day}
        loaded_at_field: reservationdate   # also lowercase column name

  - name: seeds
    database: MSITDBTSNOWGIT
    schema: SEEDS
    tables:
      - name: RESERVATIONHDRFORDEMO
        description: "Reservation header demo table with ~1.5k rows from CSV"

  