version: 2

seeds:
  - name: AccountStatus
    description: "{{ doc('account_status') }}"
    columns:
      - name: StatusCode
        description: "Unique code identifying the account status."
        tests:
          - not_null
          - unique
      - name: Description
        description: "Text description of the account status."
      - name: CreatedDate
        description: "Original date of creation in source data."
        
       

sources:
  - name: snow_source
    description: "Source tables from SNOW"
    database: MSITDBTSNOWGIT
    schema: public
    tables:
      - name: reservationhdr   # match lowercase
        description: "{{ doc('source_reservationhdr') }}"
        freshness:
          warn_after: {count: 1, period: day}
          error_after: {count: 2, period: day}
        loaded_at_field: reservationdate   # also lowercase column name

  - name: seeds
    database: MSITDBTSNOWGIT
    schema: SEEDS
    tables:
      - name: RESERVATIONHDRFORDEMO

        description: "{{ doc('source_reservationhdrfordemo') }}"

